export const CLOSEPLAYLIST='CLOSEPLAYLIST' // 关闭歌单列表
export const OPENPLAYLIST='OPENPLAYLIST' // 打开歌单列表
export const SHOWPLAYINFO='SHOWPLAYINFO' //  切换播放详情
export const SENDAUDIO='SENDAUDIO'  // 传入audio 元素
export const SENDMUSIC='SENDMUSIC' //  传入音乐对象
export const SWITCHPLAY='SWITCHPLAY' // 切换播放状态
export const SETCURTIME='SETCURTIME' // 设置当前播放时间
export const DELMUSIC='DELMUSIC' // 删除音乐
export const SELECTMUSIC='SELECTMUSIC' // 选择音乐
export const NEXTMUSIC='NEXTMUSIC'  // 下一首
export const BEFOREMUSIC='BEFOREMUSIC'  // 上一首
